# Generated by Django 3.1.4 on 2021-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='valores_sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_aire', models.FloatField()),
                ('temperatura_aire', models.FloatField()),
                ('humedad_suelo_1', models.FloatField()),
                ('humedad_suelo_2', models.FloatField()),
                ('humedad_suelo_3', models.FloatField()),
                ('humedad_suelo_4', models.FloatField()),
                ('luz', models.FloatField()),
                ('Estado_riego', models.IntegerField()),
                ('Estado_luz', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='valores_sensores_hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=25)),
                ('sumatoria', models.FloatField()),
                ('minimo', models.FloatField()),
                ('maximo', models.FloatField()),
                ('registros', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
