# Generated by Django 3.1.4 on 2021-04-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_sensor_values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores_sensores',
            name='modo_luz',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valores_sensores',
            name='modo_riego',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
