# Generated by Django 3.1.4 on 2021-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_sensor_values', '0003_calibracion_sensores_humedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracion_sensores_humedad',
            name='sensor_id',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
    ]
