# Generated by Django 3.1.4 on 2021-08-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_sensor_values', '0004_auto_20210802_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolean_choises',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('choise', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Valores_reales_humedad',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_real', models.IntegerField()),
            ],
        ),
    ]
